### ISSUE TITLE
Project End Results

### ISSUE THREAD

**Issue by jaakop** [Fisherman-s-Friends/Fisherman-s-Friends#103]
[Assignment](https://moodle.jamk.fi/mod/assign/view.php?id=627906)

Everyone to write _self-reflection_ about the project
EDIT: Also "There should be an individual self-reflection about the project from everyone **_as well as the group as a whole_**"

**Emil**
- [x] What did you do?
- [x] What went right and what went wrong?
- [x] What was difficult/fun?
- [x] What did you learn?
- [x] Group-reflection part

**Aleksandar**
- [x] What did you do?
- [x] What went right and what went wrong?
- [x] What was difficult/fun?
- [x] What did you learn?
- [x] Group-reflection part

**Leevi**
- [x] What did you do?
- [x] What went right and what went wrong?
- [x] What was difficult/fun?
- [x] What did you learn?
- [x] Group-reflection part

**Jaakko**
- [x] What did you do?
- [x] What went right and what went wrong?
- [x] What was difficult/fun?
- [x] What did you learn?
- [x] Group-reflection part

**Comment by Emiliontti** [comment]
### Emil's part
###  What did you do?
- I created the controls for the game (casting system, fishing lines, bobber logic etc.)
- I created the mini-game
- I participated in searching assets to use in the scene (boat-, fish-models etc.)
- I created the terrain system
- A small particle system for the bobber
- Composed most of the documentation until this point
- Also some small misc. stuff, like creating Exit-button for Menu Scene.

###  What went right and what went wrong?
- I'm really surprised of the state of the game, where we got it. I feel like we could've gotten it to a even better state, but the scope of the project might've not supported it. Everything else I think went quite smoothly, except there was some quite big issues with trying to meet deadlines in the group.

###  What was difficult?
- I think the most difficult thing was that time span for this time of group work was so long. It was hard to start working again, after having a small hiatus. Also group work has it's ups and downs.

###  What did you learn?
- I learned a lot from this project. Mostly about individual systems, how objects reference each other, basics of Unity usage. Also one of the biggest things was to learn how to somewhat properly use Github and Git-client Fork.

### This is for the group part
Group worked well, except with the problems with deadlines. Could've done a timeline maybe earlier in the project and tried to withhold that.

**Comment by jaakop** [comment]
# Jaakko
## What did you do?
- I created the fishes and their logic
- I created the base for the home scene
- Made the background sky with assets and initial word generation
- I made the dialog system
- Worked as a project manager by organizing meetings, tasks/issues, and timelines.
## What went right and what went wrong?
I think we have managed to create a surprising amount of functionalities and content into the game and managed to learn new things along the way. The initial planning could have been better since the different functionalities were changed many times along the way. I think this somewhat slowed us down as we didn't have a clear idea of what to do next when the current issues were done.
## What was difficult/fun
As the one in the project management role I think was difficult to assign the right-sized tasks for all, so that they had enough work but so that they didn't feel overwhelmed with the amount or the difficulty. Fun was to get to make systems that challenged my own skills in some ways and learn to code bigger projects that have a longer development time when compared to e.g. a game jam.
## What did you learn?
Project management and reporting as well as some new tricks with Unity (such as custom editors and Scriptable objects)

# Group part
We had a great group and we had really good discussions when planning the game. However, there were some challenges with timelines which maybe could've been avoided if we made a stricter schedule in the beginning.

**Comment by Laffey-chan** [comment]
# Leevi

## What did  you do?

- Created bones for the fish models
- Created simple animation for fishes
- Money and loan showing in game
- Adding money and recusing money when advancing day
- Fish pawning so they spawn outside of the camera
- Unity custom inspector for fish spawn script
- Spawning of the shark when timer hit sertain value

## What went right and what went wrong?

The project has suprising amount of funtionalities and content and we managed to learn new things along the way. The initial planning was great, but because we didn't have next issues to do when we finished the current issue.

## What was difficult/fun

I think the how long the the time was for the group project. Hard to get back to work from other stuff that happened. The fun was learning new things of doing stuff and getting somewhat better at understanding somebody's else code and seeing how they have made it and looking how would you have done it and compering them.

## What did you learn?

I learned a lot back to unity coding, like how the api worked and basic on some part of the unity, and how to use git for unity project. And how unity's player controller worked when i looked that  just for curiosity and unity event's.

## Group part

We had a great group and we had nice and helpful discussions when planning the game and when doing the game. But challenges was timelines which would have been made from the beginning

**Comment by TemkaUwU** [comment]
### What did you do?

- I Created the hook and bobber 3d models.

- I Created some of the hook’s logic (spawning the hook, stopping the hook)

- I did the Win and Lose Screens

- I Created a Pop-Up style screen to show when catching a fish

### What went right and what went wrong?
Most the code that I did seemingly works fine. The game works and looks fantastic! I think I could have done quite a bit more (procrastination is a bitch) and the game would be in an even more finished state.
### What was difficult/fun?
Most of my tasks gave me issues with me not being familiar with Unity. Mangaing my own schedule also gave me issues. but the results are worth looking through forums and videos for solutions for simple issues.
### What did you learn?
I learned quite a bit from this project I got familiar enough with Unity now that I feel for future projects, I’ll be able to pull my weight a lot better.
### Group Part
My group was Heavenly we communicated with each other when we had issues. We should have done a timeline with tight timelines, but it worked out at the end.
