### ISSUE TITLE
Module 3 Assignment

### ISSUE THREAD

**Issue by jaakop** [Fisherman-s-Friends/Fisherman-s-Friends#74]
[Assignment](https://moodle.jamk.fi/mod/assign/view.php?id=628240)
**Emil**
 - [x] Completed tasks
- [x] In-progress tasks

**Aleksandar**
- [x] Completed tasks
- [x] In-progress tasks

**Jaakko**
- [x] Completed tasks
- [x] In-progress tasks

**Leevi**
- [x] Completed tasks
- [x] In-progress tasks

**Comment by jaakop** [comment]
# Completed
## Fish collision avoidance
In order to avoid collision with the environment the fish does checks to ensure that the next waypoint is available (no collision with environment between it and current position). To do this the fish casts a ray from its position to the target. If the ray collides with the environment colliders it moves the point around it self and tries again. This is done until a suitable point is found.
```cs
protected Vector3 AvoidCollissionsWithEnv(Vector3 point)
{
    // 1 << 3 -> Check for collissions only on layermask no. 3
    while (Raycast(point, 1 << 3))
    {
	    point = RotatePointAroundFish(point, collissionAvoidanceTurnRate);
    }
    return point;
}

protected bool Raycast(Vector3 point, int layerMask)
{
    var pos = transform.position;
    var dir = point - pos;
    return Physics.Raycast(pos, dir, dir.magnitude, layerMask);
}
private Vector3 RotatePointAroundFish(Vector3 point, float amount)
{
    var pos = transform.position;
    return pos + Quaternion.AngleAxis(amount, Vector3.up) * (point - pos);
}
```

This implementation itself may cause the fish to create an infinite loop where no point is ever found. Assuming that the the point, where the fish is currently, is a valid point, we can move the point closer to the fish each iteration. This creates a spiral pattern that gets closer and closer to the fish and thus eventually finds a suitable position.
![Pasted image 20231029174630](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/10682098/47842133-0c39-472d-ad4d-98ca621ef424)
(Yellow = initial point, Red = invalid point, Green = valid point)

```cs
protected Vector3 AvoidCollissionsWithEnv(Vector3 point)
{
    var distanceModifier = 1f;
    // 1 << 3 -> Check for collissions only on layermask no. 3
    while (Raycast(point, 1 << 3))
    {
        point = RotatePointAroundFish(point, collissionAvoidanceTurnRate, distanceModifier);
        distanceModifier *= 0.9f;
    }
    return point;
}

private Vector3 RotatePointAroundFish(Vector3 point, float amount, float distanceModifier)
{
    var pos = transform.position;
    return pos + Quaternion.AngleAxis(amount, Vector3.up) * (point - pos) * distanceModifier;
}
```

Code to make the point close in on the fish.

![Pasted image 20231029181017](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/10682098/28a22114-b0e3-4172-b032-cd632246e3fd)
## Fish spawning rework
Partially as a scriptable objects demo I reworked the fish spawning to utilize scriptable objects.
```cs
[CreateAssetMenu(fileName = "Data", menuName = "ScriptableObjects/FishSpawnObject")]
public class FishSpawnObject : ScriptableObject
{
    public GameObject prefab;
    [Tooltip("Amount of fish to spawn")]
    public int amount;
    [Range(0, 10), Tooltip("Weight of this type when it is selected randomly")]
    public int weight;
    [Tooltip("Limit the fish to only one on the screen at a time")]
    public bool Limit;
}
```
Also to support spawning groups of fish instead of only random fish. This makes the boid fish feel better as it ensures that if they are spawned, a group of the will be spawned. 
![Pasted image 20231029182449](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/10682098/d28d2a21-cdb8-416f-abbf-a94bb4af8992)
## Home
![Pasted image 20231029182627](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/10682098/4627ed19-281b-4df5-b9ea-f88545ca9573)
I started creating home scene, where the player goals are presented. The goal of the player is to payback a loan from the loanshark. I created the new scene, scene management and timer to the fishing scene to return the player to the home scene. I've also created a base for the loan payback feature that on top of which can the paying, winning and losing mechanics be build on.
![Pasted image 20231003200755](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/10682098/6b941f45-c075-421a-9528-36c9e8ba1999)
# In progress
For the future I plan to only help and guide the other to get them coding as well.

**Comment by Laffey-chan** [comment]
# Completed

## Advancing next day

This was simple to implement because it was just using the session manager that has function to advance next day it was just adding the day counter also to this when advancing to next day 
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/25053472/eede7778-79b8-42dc-ae25-161c87acdab1)

## Adding the money from fishes

This i added to the player controlscript that has information about the fish that is in the hook so i could do scriptable object and just getting the reference from the fishobject and the the fish value. So the money is added to the player when the minigame end, and the recast also dosen't call the money function so it wouldent give the reference error for the script

![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/25053472/15ff33ae-dfd1-4ac6-99bf-a5a080d50f10)
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/25053472/04f27b45-808e-4581-94a5-d18b3f641b72)
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/25053472/e19d1573-60f9-4fae-a3e2-028e664addf4)

## Money and loan text for menu and in game

There was money already but i needed to add loan text to the menu scene and then also needed to make the money and load text to the fishing part and there i used the sessioncontroller to update the text using event when scene load it calls the update text function
![image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/25053472/a42a97f0-caca-4beb-80f4-8c97bc53ac0b)


# In progress

Maby doing icons for the money and loan and changing how the ui looks

**Comment by Emiliontti** [comment]
#Completed Tasks
Make the fish catch on the hook
The fish needed to be caught on the hook. So, I made a child object for the hook, with no mesh, and a bigger collider. This collider would make collision entry, when the first fish puts it “next-target-location” inside the collider. Then the fish would take the transform of the hook, turn towards it and start swimming towards the hook and getting to a certain distance of it, stop. After this sequence the Minigame would start.
 
In the HookScript, the 2nd collider of the hook has a OnTriggerEnter, that detects the fishs next spawn target, and defines that fish as the “closestFish”, so we get a reference for the instance to the fish we’re dealing with.

In the FishScript I added the following methods, to get the target of the hook, and make that fish swim for the hook. The fish would stop, when it reached a certain distance from the hook, but also continue its journey, if the goingForHook -boolean was turned to false (i.e., the fish would swim away from the hook – used when the player resets the cast without catching the fish) 
Minigame
We needed to make the game a bit more interesting, and per our plan from the previous documentation, I started to make the minigame for that purpose. 

The minigame consist of several UI elements. There’s a reference to the fish getting caught and getting the attributes (the speed of the fish icon, the amount of value needed and the “smoothness” of the movement of the fish icon) to the game. The code behind it makes it work in the following way:
1.	(the minigame gets triggers when a fish sets it next target inside the hooks collider, swims towards the hooks position and gets “caught”)
2.	The orange fish icon moves on it’s own inside the constrained blue area on the X-axis using math and update-method
a.	The fish derives it’s moving math from the fish that was previously caught on the hook. The scriptable objects that define the behaviour labelled as “Default”, “Lazy” and “Quick” pointing to the movement of the fish and also the max value of the progress bar.
3.	The green square can be moved by the player. The player can use their mouse, or the keyboard to move the square. 
4.	When the square is on the fish, the green bar fills up. If it’s in the center of the fish icon, it fills it faster
5.	When the bar fills up completely, the minigame ends and the fish gets caught...

The referencing was a big problem when making the game in the script, because both the hook and the fish are both instantiated in the code. Also, the minigame-object itself is inactive before a fish is actually caught on the hook.
 
The following code is from the MinigameScript, and it gets the behaviour of the fish, and sets the slider max-value (makes the fish take longer to catch)
 
The update function makes the area move, as well as adjust the progress bar and calculates new positions for the fish-icon to travel to and makes it move.
  
The MinigameScript also houses the method to get the fish-behaviour from the caught fish scriptable objects: 

Also, the moving the green square at the minigame is handled inside the MinigameScript’s MinigameMovement-method. The calculations make sure, that the square (and also the fish) stay inside of the designated area.

Because of the referencing issues (minigame being unactive until being made active by the fish catching the hook), the PlayerController acts as a link to pass the information of the fish caught on the hook. It also checks that the fish is close enough to the hook and not still swimming towards it, before starting the minigame.

The PlayerController also enables for the player to let the fish go from the hook, or it destroys the fish, when you complete the minigame (get max value on the progress bar)

#In-progress
I’m working on doing the following tasks (quit game & return to home). So basically, I want to make it so that you can return from the game scene to the home scene, and also that you can quit them game from the home scene.

**Comment by TemkaUwU** [comment]
### Completed 

**Made the hook stop** 

<img width="266" alt="4" src="https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510355/f2c24483-d82a-495e-bc98-3d711c3bdf94">


Made a new action in the player input action 

 
<img width="273" alt="image" src="https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510355/75f4c9ee-f2b2-44b1-90ad-57c8e34f0282">


This checks if the hook has already been cast and then disables its gravity to make it stop falling and turns on its collisions. 

**Made bobber and hook model** 


<img width="57" alt="2" src="https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510355/102e6c93-4496-4714-af97-4697ccf89bb1">
<img width="108" alt="3" src="https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510355/5682a725-973a-431f-8dbb-17f28556caae">


Went into blender and made these to replace the cube placeholders 

### In Progress

Make Splash screen scenes for Win, Lose and Catch fish
![Screenshot 2023-11-05 234339](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/143510355/2081a1f1-7769-41ea-b8c7-670d25ed1673)

**Comment by Emiliontti** [comment]
All doned! PDF Returned
